### ISSUE TITLE
Niedziałające strony błędów

### ISSUE THREAD

**Issue by MervinDelfin** [informatyzacja/LigaPWr#4]
Nie działają mi strony błędów np. 404.
Dostaje domyślny error nginxowy zamiast ładnej strony:
<img width="1679" alt="Zrzut ekranu 2024-03-17 o 12 18 09" src="https://github.com/informatyzacja/LigaPWr/assets/34074234/516bad6d-2841-48ac-b871-3ccf5a3a925a">

@lolex565 u ciebie działa?

**Comment by lolex565** [comment]
Okej, znalazłem błąd, i faktycznie, customowe errory wywalało tylko do plików a nie do takich "pustych" endpointów, dodałem w konfiguracji nginxa proxy_intercept_errors, i u mnie zaczęło działać poprawnie
