### ISSUE TITLE
Brak zaokrąglonych rogów

### ISSUE THREAD

**Issue by MervinDelfin** [informatyzacja/LigaPWr#6]
Brak zaokrąglonych rogów w */tabela* jeżeli wybierzemy jakiś sport. W tabeli na wszystkie sporty działa poprawnie.
<img width="1727" alt="Zrzut ekranu 2024-03-18 o 14 18 00" src="https://github.com/informatyzacja/LigaPWr/assets/34074234/93012a4f-2d1b-4013-a3e4-27f2dee180bf">

**Comment by MaksymilianWojnowski** [comment]
Fixed
